import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Bell } from 'lucide-react';
import UserProfileDropdown from '../common/UserProfileDropdown';
const HeaderSimple = ({ user, onNavigate }) => {
    const handleSignOut = () => {
        // Simple sign out
        onNavigate?.('/');
    };
    return (_jsx("header", { className: "bg-white shadow-sm border-b border-sas-gray-200 sticky top-0 z-40", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-8 h-8 bg-gradient-to-br from-sas-blue-600 to-sas-purple-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-sm", children: "E" }) }), _jsxs("div", { className: "hidden sm:block", children: [_jsx("h1", { className: "text-xl font-bold text-sas-gray-900", children: "EducatorEval" }), _jsx("p", { className: "text-xs text-sas-gray-500 -mt-1", children: "Excellence in Education" })] })] }), _jsx("div", { className: "flex-1 max-w-2xl mx-4", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx(Search, { className: "w-5 h-5 text-sas-gray-400" }) }), _jsx("input", { type: "text", placeholder: "Search...", className: "w-full pl-10 pr-4 py-2 border border-sas-gray-300 rounded-lg focus:ring-2 focus:ring-sas-blue-500 focus:border-transparent text-sm" })] }) }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("button", { className: "relative p-2 text-sas-gray-600 hover:text-sas-gray-900 hover:bg-sas-gray-100 rounded-lg transition-colors", children: [_jsx(Bell, { className: "w-6 h-6" }), _jsx("span", { className: "absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-xs rounded-full flex items-center justify-center font-bold", children: "3" })] }), user ? (_jsx(UserProfileDropdown, { user: user, onSignOut: handleSignOut, onNavigate: onNavigate, notificationCount: 3 })) : (_jsx("button", { onClick: () => onNavigate?.('/login'), className: "px-4 py-2 bg-sas-blue-600 text-white rounded-lg hover:bg-sas-blue-700 transition-colors text-sm font-medium", children: "Sign In" }))] })] }) }) }));
};
export default HeaderSimple;
