// Core Type Definitions for Educational Employee Experience Platform
export const DivisionsAndDepartments = {
    elementary: [
        "Kindergarten",
        "1st Grade",
        "2nd Grade",
        "3rd Grade",
        "4th Grade",
        "5th Grade",
        "Special Education",
        "ESL/ELL",
        "Arts & Electives",
        "PE & Health",
    ],
    middle: [
        "6th Grade",
        "7th Grade",
        "8th Grade",
        "English Language Arts",
        "Mathematics",
        "Science",
        "Social Studies",
        "Special Education",
        "ESL/ELL",
        "Arts & Electives",
        "PE & Health",
    ],
    high: [
        "English",
        "Mathematics",
        "Science",
        "Social Studies",
        "World Languages",
        "Fine Arts",
        "Career & Technical Education",
        "Special Education",
        "ESL/ELL",
        "PE & Health",
        "Guidance & Counseling",
    ],
    early_learning_center: [
        "Pre-K 3",
        "Pre-K 4",
        "Head Start",
        "Early Intervention",
        "Family Services",
    ],
    central_admin: [
        "Curriculum & Instruction",
        "Special Education Services",
        "Technology",
        "Human Resources",
        "Finance & Operations",
        "Communications",
        "Professional Development",
        "Student Services",
        "Assessment & Accountability",
    ],
};
